# This is an example .gitlab-ci.yml file for running pytest
# on each commit in a Python project using a pip environment.

# Define the job stages
stages:
  - test

# Define the test job
test:
  image: python:3.10

  # Activate the pip environment and install dependencies
  before_script:
    - python -m venv mheats
    - source mheats/bin/activate
    - pip install --upgrade pip
    - pip install multiheats

  # Run the tests using pytest
  script:
    - python -m pytest tests/

