# This is an example .gitlab-ci.yml file for running pytest
# on each commit in a Python project using a conda environment.

# Define the job stages
stages:
  - test

# Define the test job
test:
  image: continuumio/miniconda3:latest

  # Activate the conda environment and install dependencies
  before_script:
    - conda env create -f environment.yml
    - source activate multiheats

  # Run the tests using pytest
  script:
    - python -m pytest tests/

